.TH flowgrind 1 "June 2009" "" "Flowgrind Manual"

.SH NAME
flowgrind-stop \- helper tool for the flowgrind network performance measurement tool daemon.
.SH SYNOPSIS
flowgrind-stop
.B -h|-v
.br
flowgrind-stop HOST[:PORT] [...]

.SH DESCRIPTION
.B flowgrind-stop
is a helper tool for the flowgrind distributed network performance measurement tool. Using
.B flowgrind-stop
any
.B flowgrindd
daemon can be instructed to terminate all active flows.
This can be used to stop all tests in case the controller lost connection with the daemons.

.SH OPTIONS

.TP
.B -h
Show help and exit.

.TP
.B -v
Show version and exit.

.SH SEE ALSO
flowgrind(1),
flowgrindd(1)
