.TH "flowgrindd" "9" "August 2013" "" "Flowgrind Manual"
.SH "NAME"
flowgrindd \- network performance measurement tool daemon
.SH "SYNOPSIS"
flowgrindd
.B \-p#|-b addr|\-h|\-v|\-d|\-w DIR/
.br 
flowgrindd [options]

.SH "DESCRIPTION"
.B flowgrindd
is the daemon for the flowgrind distributed network performance measurement tool. Using the
.B flowgrind
controller, tests can be setup between hosts running
.BR flowgrindd ","
the flowgrind daemon.

Flowgrind performs extensive TCP tests. On systems running Linux or FreeBSD flowgrindd collects and reports the TCP metrics returned by the TCP_INFO socket option, such as the size of the congestion window or the RTT.

The flowgrind daemon needs to be running on every host that is supposed to be endpoint of a flow.

.SH "OPTIONS"
.TP 
.B \-h
Show help and exit.

.TP 
.BR \-p " #"
Port the XML\-RPC server should listen on.

.TP 
.BR \-b " addr"
Address the XML\-RPC server should listen on. An easy way to enable support for IPv6 control-connections
is to specify the IPv6 wildcard address "::".

.TP
.BR \-c " #"
Bound daemon to specific CPU. First CPU is 0.

.TP 
.B \-v
Show version and exit.

.TP
.B \-w " DIR/"
Specify target directory for dump files. Compiling flowgrind with libpcap support is required. Remember, dumps are save on the machine where the daemon runs and not local.

.TP 
.B \-d
Do not daemonize, increase debug verbosity. Add multiple times to increase debug verbosity further.

.SH "SEE ALSO"
flowgrind(1),
flowgrind\-stop(1)

